### ISSUE TITLE
Idea for a simple C++20 solution 

### ISSUE THREAD

**Issue by Cons-Cat** [gwiazdorrr/CxxSwizzle#7]
I noticed that [vector_base.h](https://github.com/gwiazdorrr/CxxSwizzle/blob/master/include/swizzle/detail/vector_base.h) has hard-coded swizzling identifiers. There are infinite reasonable swizzling patterns, but only finite hard-coded ones in that file. I wondered if C++20 could abstract this. Here's what I came up with. 

As far as I can tell, this scales fairly efficiently to arbitrary length swizzles with arbitrary combinatorics.
```cpp
#include <string>
#include <array>
#include <iostream>
#include <type_traits>

template<size_t N>
struct StringLiteral {
    constexpr StringLiteral(const char (&str)[N]) {
        std::copy_n(str, N, value);
    }
    
    char value[N];
};

template<StringLiteral str>
consteval bool validate_swizzle(){
    constexpr auto strlen = sizeof(str.value) - 1;
    constexpr std::string_view strv = str.value;

    // strv.contains("xyz") only works in C++23 ...

    if constexpr (strlen == 1) {
        for (auto& s : strv) {
            if (s != 'x'
             && s != 's'){
                return false;
            }
        }
    }
    if constexpr (strlen == 2) {
        for (auto& s : strv) {
            if (s != 'x' && s != 'y' && s != 'u' && s != 'v'
             && s != 't'){
                return false;
            }
        }
    }
    if constexpr (strlen == 3) {
        for (auto& s : strv) {
            if (s != 'x' && s != 'y' && s != 'z'
             && s != 'r' && s != 'g' && s != 'b'
             && s != 'p'){
                return false;
            }
        }
    }
    if constexpr (strlen >= 4) {
        for (auto& s : strv) {
            if (s != 'x' && s != 'y' && s != 'z' && s != 'w'
             && s != 'r' && s != 'g' && s != 'b' && s != 'a'
             && s != 'q'){
                return false;
            }
        }
    }
    
    return true;
}

template<StringLiteral str>
inline consteval std::array<char, sizeof(str.value)-1> make_char_array() {
    std::array<char, sizeof(str.value)-1> arr;
    constexpr auto strlen = sizeof(str.value) - 1;
    constexpr std::string_view strv = str.value;
    for(int i = 0; i < strlen; i++) {
        arr[i] = str.value[i];
    }
    return arr;
}

template<typename T, size_t N>
struct Vec {
    std::array<T, N> data;
    T& operator[](std::integral auto index) {
        return data[index];
    }
    
    template<StringLiteral str>
    Vec<T, sizeof(str.value)-1> d() {
        static_assert(validate_swizzle<str>(), "This swizzle is invalid.");
        constexpr auto strlen = sizeof(str.value)-1;

        Vec<T, strlen> vector;
        constexpr std::array<char, strlen> arr = make_char_array<str>();
        char_to_index<T, strlen, arr>(vector, *this);
        return vector;
    }
};

template<typename T, int N, auto str>
inline void char_to_index(auto& vector_out, auto& vector_in) {
    constexpr int i = N - 1;
    char v = str[i];
    if (v == 'x' || v == 'r' || v == 'u' || v == 's') {
        vector_out[i] = vector_in[0];
    }
    else if (v == 'y' || v == 'g' || v == 'v' || v == 't') {
        vector_out[i] = vector_in[1];
    }
    else if (v == 'z' || v == 'b' || v == 'p') {
        vector_out[i] = vector_in[2];
    }
    else if (v == 'w' || v == 'a' || v == 'q') {
        vector_out[i] = vector_in[3];
    }
    
    if constexpr (i > 0) {
        char_to_index<T, N-1, str>(vector_out, vector_in);
    }
}

int main() {
    Vec<float, 3> foo{
        .data = {0, 1, 2},
    };
    Vec<float, 3> swizzle_3 = foo.d<"xyz">();
    Vec<float, 5> swizzle_5 = foo.d<"xyzxz">();
    Vec<float, 10> swizzle_10 = foo.d<"xyzwzywzyx">();

    // Print out to prevent optimizing away all the work.
    for(auto& v : swizzle_5.data){
        std::cout << v << '\n';
    }
    return EXIT_SUCCESS;
}
```
You can paste this into https://godbolt.org and use ``x64 msvc v.19-latest`` with the flags ``/std:c++20 /O2`` or GCC 10 / 11 with ``-std=c++20 -O3`` to try messing around with it. GCC unfortunately hasn't made strings constexpr yet. This seems to basically work. It's somewhat complex, because it involves a recursive template function. I had a simper version that worked iteratively, but C++20 doesn't allow forcing inline for-loops (and MSVC doesn't have an extension to do it), so the compiler couldn't elide string comparisons. This appears to be a low-cost abstraction when compiler optimizations are enabled. There may be some ways to simplify it further. I tried overloading ``Vec``'s ``[]`` operator to take a string in, but I couldn't get it working so far.

I got the basic idea of this from [an article](https://ctrpeach.io/posts/cpp20-string-literal-template-parameters/) I read a little while ago. The strategy seems reasonably flexible.

What do you think? Is a solution like this worth pursuing further?

**Comment by Cons-Cat** [comment]
As I can only access MSVC from Compiler Explorer, I haven't actually been able to test this code beyond ensuring it compiles and checking the dissassembly.

**Comment by Cons-Cat** [comment]
I've fixed some issues in the example now.

**Comment by gwiazdorrr** [comment]
AFAIK with GLSL you can have max 4 components in your swizzle, so `.xxxx` is ok, but `.xxxxx` - not really. So the list is exhaustive.

But if we put this aside, I think your syntax could be improved if you aim to drop the `<>` and maybe go for a string literal (say `_v`) like `Vec<float, 5> swizzle_5 = foo.d("xyzxz"_v);`. Still not perfect, but if you're desperate for long swizzles this might be the way.

**Comment by Cons-Cat** [comment]
> I think your syntax could be improved if you aim to drop the `<>` and maybe go for a string literal (say `_v`) like `Vec<float, 5> swizzle_5 = foo.d("xyzxz"_v);`.

Hm, it is necessary that the string literal is ``constexpr`` in order for it to be passed into the recursive template function that expands into the array-assignments. I like that because it leaves all of the work to the compiler, except for constant-folding. However, I've implemented what you suggest:
```cpp
#include <algorithm>
#include <iostream>

template<size_t N>
struct String
{
    static constexpr size_t length = N - 1;
    char str[length];

    consteval String(const char(&in)[N]) : str{} {
        std::copy(in, in + length, &str[0]);
    }
};
template <String str> consteval auto operator ""_v() { return str; }

template<typename T, size_t N>
struct Vec {
    T data[N];
    T& operator[](auto index) {
        return data[index];
    }

#ifdef _MSC_VER
    __force_inline
#endif
#ifdef __clang__
    __attribute__((always_inline))
#endif
#ifdef __GNUG__
    __attribute__((always_inline))
#endif
    auto swizzle(auto&& str) {
        Vec<T, str.length> vector_out;
        for (int i = 0; i < str.length; i++) {
            char v = str.str[i];
            if (v == 'x' || v == 'r' || v == 'u' || v == 's') {
                vector_out[i] = this->data[0];
            }
            else if (v == 'y' || v == 'g' || v == 'v' || v == 't') {
                vector_out[i] = this->data[1];
            }
            else if (v == 'z' || v == 'b' || v == 'p') {
                vector_out[i] = this->data[2];
            }
            else if (v == 'w' || v == 'a' || v == 'q') {
                vector_out[i] = this->data[3];
            }
        }
        return vector_out;
    }
};

auto main() -> int {
    Vec<int, 3> v3 = {rand(),rand(),rand()};
    std::cout << v3.data[0] << '\n';
    std::cout << v3.data[1] << '\n';
    std::cout << v3.data[2] << "\n\n";
    Vec<int, 5> v5_1 = v3.swizzle("xyzxy"_v);
    std::cout << v5_1.data[0] << '\n';
    std::cout << v5_1.data[1] << '\n';
    std::cout << v5_1.data[2] << '\n';
    std::cout << v5_1.data[3] << '\n';
    std::cout << v5_1.data[4] << '\n';
    Vec<int, 5> v5_2 = v3.swizzle("yzzxy"_v);
    std::cout << v5_2.data[0] << '\n';
    std::cout << v5_2.data[1] << '\n';
    std::cout << v5_2.data[2] << '\n';
    std::cout << v5_2.data[3] << '\n';
    std::cout << v5_2.data[4] << '\n';
}
```
The only issue is that ``inline`` there is really quite a suggestion, rather than a guarantee. That recursive template in the OP makes the value of the swizzle embedded into the type itself, so constant-folding is _always_ possible. This new approach does not provide constant-folding on ``-O3`` in GCC unless that swizzle function is only instantiated once per unique string-length that is passed into it. In this case, because I perform two swizzles on some string of length 5 characters, constant-folding doesn't occur, and the codegen is extremely pessimized.

Adding the GCC attribute ``__attribute__((always_inline))`` to the ``swizzle()`` method completely solves that problem, but that isn't portable across all compilers. MSVC and Clang/GCC have different attributes, so ``#ifdef``s are necessary. This compiles and works correctly with GCC, but Clang and MSVC do not compile. I'm not quite sure why. Reflection TS in a future C++ would make this much easier.
